sudo: false
language: node_js
cache:
  bundler: true
  directories:
  - node_modules
node_js:
- '0.10'
deploy:
  provider: npm
  skip_cleanup: true
  clean_up: false
  email: serveradmin@octoblu.com
  on:
    tags: true
    all_branches: true
  api_key:
    secure: HhompYv2BcyP4KviAFbyGUbNLRMQxcZ9Wx7+6uhKHTDcz+mfeGfwTIFr9A2XLai0QsvZsbqfvdG6SKnjvASL1I8tYR9ivXROblUuY/C8WN0afxxyiK2QAZf41q7Ls+zGSyOKvGZ342aAdsQwX04X8B6ALKKuK0ys2+kKmCqVRYw=
