language: node_js
node_js:
- '0.10'
before_install:
  - npm install npm -g
deploy:
  - provider: npm
    skip_cleanup: true
    clean_up: false
    email: serveradmin@octoblu.com
    api_key:
      secure: "lr4mJq8Itkkr0QUN6pwtgEIg7Ro8+cNgJrz+EJnpGUg7VflJtgxn7lYtVcVpc6Qv/n2esuDMxL5HKj+rvfHQQ1JQw2u1vNi24WQnwjVJfjgwRirpxVguraqHnLYh1Y5MCRSJRCo67f9l9jg1VU0qiAFjE6SXlZ1rtW8FbFQlAsQ="
    on:
      tags: true
      all_branches: true
